set number
set nocompatible
filetype plugin on
syntax on
color molokai
set autoindent
set wrap
set linebreak
set t_Co=256
set guifont=Pragmata\ Medium\ 8
" set guioptions-=m  "remove menu bar
set guioptions-=T  "remove toolbar
set guioptions-=r  "remove right-hand scroll bar
set guioptions-=L  "remove left-hadn scrollbar
" NERDTree configuration
let NERDTreeIgnore=['\.pyc$', '\.rbc$', '\~$']
nmap <Leader>n :NERDTreeToggle<CR>
