#!/bin/sh
#~/.xinitrc
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"
xfce4-power-manager &
nitrogen --restore &
dropboxd &
#exec ck-launch-session dbus-launch --sh-syntax --exit-with-session ~/.bin/startob
#exec ck-launch-session gnome-session
#exec ck-launch-session dbus-launch --sh-syntax --exit-with-session ~/.bin/startdwm
exec ck-launch-session dbus-launch subtle
